[tools]
atuin = "latest"
bat = "latest"
bun = "latest"
delta = "latest"
fzf = "latest"
lsd = "latest"
node = "lts/jod"
ripgrep = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"

[settings]

[settings.npm]
package_manager = "bun"
